BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rugix-rpi-tryboot"
BBFILE_PATTERN_meta-rugix-rpi-tryboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rugix-rpi-tryboot = "6"

LAYERDEPENDS_meta-rugix-rpi-tryboot = "core meta-rugix-core"
LAYERRECOMMENDS_meta-rugix-rpi-tryboot = ""
LAYERSERIES_COMPAT_meta-rugix-rpi-tryboot = "kirkstone scarthgap"

IMAGE_CLASSES += "rugix-wks"
RUGIX_WKS_FILE ?= "sdimage-rugix-rpi-tryboot.wks.in"
RUGIX_SLOTS ?= "boot:2 system:4"
