BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rugix-qemu-arm64-uboot"
BBFILE_PATTERN_meta-rugix-qemu-arm64-uboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rugix-qemu-arm64-uboot = "10"

LAYERDEPENDS_meta-rugix-qemu-arm64-uboot = "core meta-rugix-core"
LAYERRECOMMENDS_meta-rugix-qemu-arm64-uboot = "lts-u-boot-mixin"
LAYERSERIES_COMPAT_meta-rugix-qemu-arm64-uboot = "scarthgap"

IMAGE_CLASSES += "rugix-wks"
RUGIX_WKS_FILE ?= "qemu-arm64-rugix-uboot.wks"
RUGIX_WKS_FILE_DEPENDS ?= "u-boot-boot-image"
RUGIX_SLOTS ?= "system:2"
