BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rugix-qemu-x86_64-grub"
BBFILE_PATTERN_meta-rugix-qemu-x86_64-grub = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rugix-qemu-x86_64-grub = "10"

LAYERDEPENDS_meta-rugix-qemu-x86_64-grub = "core meta-rugix-core"
LAYERSERIES_COMPAT_meta-rugix-qemu-x86_64-grub = "scarthgap"

IMAGE_CLASSES += "rugix-wks"
RUGIX_WKS_FILE ?= "qemu-x86_64-rugix-grub-efi.wks"
RUGIX_WKS_FILE_DEPENDS ?= "efi-boot-image"
RUGIX_SLOTS ?= "system:2"
